name: Tests and Code Quality Checks.

on:
  workflow_call:

jobs:
  tests_and_linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8'] #, '3.9', '3.10' ]
    steps:
    - uses: actions/checkout@v3
    - uses: arduino/setup-task@v1
    - name: Setup python version.
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry.
      uses: snok/install-poetry@v1
      with:
        version: 1.1.13
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install dependencies.
      run: task init
    - name: Run linters.
      run: |
        source .venv/bin/activate
        task lint

    - name: Run tests.
      run: |
        source .venv/bin/activate
        task tests
